# XCodegen file for generating macOS build target, for the swift
# frontend.
name: kilo
configs:
  Debug: debug
  Beta: release
  AppStore: release
options:
  bundleIdPrefix: com.kilo.app
  deploymentTarget:
    macOS: "14.4"
targets:
  kilo:
    type: application
    platform: macOS
    deploymentTarget: "14.4"
    sources: [src]
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: build/kilo.dylib
        root: build
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.kilo.app
      entitlements:
        com.apple.security.app-sandbox: true
        com.apple.security.network-client: true